name: Validate Docker Environment

# This workflow validates the Docker environment configuration
# It does not build the full image due to network restrictions in CI

on:
  push:
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - '.dockerignore'
      - 'scripts/cline-integration.sh'
      - '.github/workflows/validate-docker.yml'
  pull_request:
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - '.dockerignore'
      - 'scripts/cline-integration.sh'
      - '.github/workflows/validate-docker.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate Docker Configuration
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Validate docker-compose.yml syntax
        run: |
          docker compose config > /dev/null
          echo "✓ docker-compose.yml is valid"
      
      - name: Run validation script
        run: |
          chmod +x scripts/validate-docker.sh
          ./scripts/validate-docker.sh
      
      - name: Check Dockerfile syntax
        run: |
          docker build --check -f Dockerfile . || true
          echo "✓ Dockerfile syntax checked"
      
      - name: Validate cline-integration.sh
        run: |
          bash -n scripts/cline-integration.sh
          echo "✓ cline-integration.sh syntax is valid"
      
      - name: Check documentation
        run: |
          # Check that documentation files exist and have content
          test -s DOCKER.md && echo "✓ DOCKER.md exists"
          test -s DOCKER_WORKFLOWS.md && echo "✓ DOCKER_WORKFLOWS.md exists"
          test -s .env.example && echo "✓ .env.example exists"
          test -s Makefile && echo "✓ Makefile exists"
      
      - name: Validate Makefile targets
        run: |
          make help
          echo "✓ Makefile is valid"
      
      - name: Summary
        run: |
          echo "=================================="
          echo "Docker environment validation completed successfully!"
          echo "=================================="
          echo ""
          echo "Note: Full Docker build is skipped in CI due to network restrictions."
          echo "To build locally, run: docker compose build"
